# -*- coding: utf-8 -*-
"""100DaysOfCodingPythonDay2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y4pIcZ9c7q0l3N-HX0GVNEoG4a97Hyly

Write a program that adds the digits in a 2 digit number. e.g. if the input was 35, then the output should be 3 + 5 = 8
"""

a = 54
b = 83
c = a + b
print(c)

"""BMI Calculator"""

weight = int(input('Please enter your weight in kg:'))
height = float(input('Please enter your height in meters:'))
BMI_Calc = weight/(height * height)
message = f'Based on your input of weight = {weight} and height = {height}, your BMI is {BMI_Calc}'
print(message)

"""Brand Name Generator"""

name = input("What is your name?")
age = input('How old are you?')
pet = input("What's your favourite pet?")
pet_name = input("what's the name of your pet?")
brandname = (pet + pet_name)
print(f"Hi Pretty {name}, Wow you are {age} years old. It's amazing that your favourite pet is {pet} and your pet's name is {pet_name}. {pet_name} should be called {brandname}. :)")

"""Rounding Number, Exponient"""

print(round(8/3, 3))
print(8 // 3)

"""Your Life in Weeks - How Many Weeks Do you have left if your are to live until 90 years old?"""

OneYear = 365
Weeks = 52
Months = 12
Age = int(input("Please enter your age:"))
Your_life_in_Weeks_in_Two_Years = Weeks * 2
Remainingyears = 90 - Age
Your_live_in_weeks = Remainingyears * 52
Your_live_in_days = Remainingyears * 365
Your_life_in_months = Remainingyears * 12
message = f"Here is your remaining life in Weeks, days and months:\n You have {Your_live_in_weeks} weeks, {Your_live_in_days} days, and {Your_life_in_months} months to live.\n Make the best of it!"
print(message)

"""Tip Calculator"""

print("Welcome To Your Tip Calculator...Calculate Away :)")
bill = int(input("What is your total bill?\n"))
percentage = int(input("What percentage tip would you like to give?\n"))
no_of_people = int(input("How many people will be splitting the bill?\n"))
tip = percentage/100 * bill
total_bill_with_tip = tip + bill
bill_per_person = total_bill_with_tip/no_of_people
final_amount = round(bill_per_person, 2)
final_amount = "{:.2f}".format(bill_per_person)
message = f"Each person should pay £{bill_per_person}"
print(message)