# -*- coding: utf-8 -*-
"""100DaysOfCodingPythonDay3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCaS6YdOlk3PK1aVAogmB23CHTTQJ8zP

**If/Else Statement: Check Odd and Even Number**

Write a program that works out whether if a given number is an odd or even number.
"""

print('Welcome To Check Odd and Even Number')
#user enters a chosen number
number = int(input('Enter the number you want to check:\n'))
if (number % 2) == 0:
    print(f'{number} is an even number\n')
else:
  print(f'{number} is an odd number\n')

"""**Nested if statements and elif statements: BMI Calculator 2.0**

Write a program that interprets the Body Mass Index (BMI) based on a user's weight and height.

It should tell them the interpretation of their BMI based on the BMI value.

Under 18.5 they are underweight
Over 18.5 but below 25 they have a normal weight
Over 25 but below 30 they are slightly overweight
Over 30 but below 35 they are obese
Above 35 they are clinically obese.

The BMI is calculated by dividing a person's weight (in kg) by the square of their height (in m):
"""

print('Welcome To Your BMI Calculator')
#user enters weight in kg and height in meters
weight = float(input('Please enter your weight in kg:'))
height = float(input('Please enter your height in meters:'))
#BMI calculator rounds up the figure
BMI_Calc = round(weight/(height * height))
if BMI_Calc < 18.5:
  print(f'Your BMI is {BMI_Calc}, you are under weight')
elif BMI_Calc <= 25:
  print(f'Your BMI is {BMI_Calc}, your weight is normal')
elif BMI_Calc <= 30:
  print(f'Your BMI is {BMI_Calc}, you are slightly obessed')
elif BMI_Calc <= 35:
  print(f'Your BMI is {BMI_Calc}, you are obessed')
else:
  print(f'Your BMI is {BMI_Calc}, you are clinically obessed')

"""**Leap Year Calculator:**

Write a program that works out whether if a given year is a leap year. A normal year has 365 days, leap years have 366, with an extra day in February. The reason why we have leap years is really fascinating, this video does it more justice:
"""

year = 2020
is_leapyear = year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)

print(is_leapyear)

import calendar
print(calendar.isleap(2022))

"""**Leap Year Calendar Calcuator:**"""

print('Welcome To Leap Year Calendar')
# User enters the year
year = int(input("Enter Year: "))

# Leap Year Check
if year % 4 == 0 and year % 100 != 0:
    print(year, "is a Leap Year")
elif year % 100 == 0:
    print(year, "is not a Leap Year")
elif year % 400 ==0:
    print(year, "is a Leap Year")
else:
    print(year, "is not a Leap Year")

"""**Order Calculator:**

Congratulations, you've got a job at Python Pizza. Your first job is to build an automatic pizza order program.

Based on a user's order, work out their final bill.

Small Pizza: $15

Medium Pizza: $20

Large Pizza: $25

Pepperoni for Small Pizza: +$2

Pepperoni for Medium or Large Pizza: +$3

Extra cheese for any size pizza: + $1
"""

#This is the pizza information
'''
Small_Pizza = 15
Medium_Pizza = 20
Large_Pizza = 25
Add_Pepperoni = ('Y')
Add_Cheese = ('N')
Small Pizza Topping = 2
Medium and Large Pizza Topping = 3
Cheese = 1
'''

print('Welcome To Python Pizza. Please Place Your Order')
Size = input('What pizza size do you want to order? S, M or L:')
Topping = input('Do you want pepperoni? Y or N:')
Extra_Cheese = input('Do you want extra cheese? Y or N:')


bill = 0

if Size == 'S' or Size == 's':
  bill += 15
elif Size == 'M' or Size == 'm':
  bill += 20
elif Size == 'L' or Size == 'l':
  bill += 25
else: print("choose a size!")

if Topping == 'Y' or Topping == 'y':
  if Size == 'S' or Size == 's':
    bill += 2
  else:
    bill += 3

if Extra_Cheese == 'Y' or Extra_Cheese == 'y':
  bill += 1
else:
  bill += 0
final_bill = bill
print(f'Your total bill is: £{final_bill}.')

"""**Love Compatibility Calculator:**

You are going to write a program that tests the compatibility between two people.
"""

print('Welcome To Your Love Calculator:')
Name1 = input("Enter Your Full Name:")
Name2 = input("Enter Your Partner's Full Name:")
Names = (Name1 + Name2).lower()

true_score = 0
love_score = 0

for letter in set('true'):
  true_score += Names.count(letter)
for letter in set('love'):
  love_score += Names.count(letter)

total_score = int(str(true_score) + str(love_score))

if total_score < 10 or total_score > 90:
  message=(f'You are {total_score}% compatible, you go together like coke and mentos.')
  print(message)

elif total_score >= 40 and total_score <= 50:
  message = (f'You are {total_score}% compatible, you are alright together.')
  print(message)

else:
  message = (f'You are {total_score}% compatible.')
  print(message)

"""**Treasure Island Game**"""

print('''
*******************************************************************************
          |                   |                  |                     |
 _________|________________.=""_;=.______________|_____________________|_______
|                   |  ,-"_,=""     `"=.|                  |
|___________________|__"=._o`"-._        `"=.______________|___________________
          |                `"=._o`"=._      _`"=._                     |
 _________|_____________________:=._o "=._."_.-="'"=.__________________|_______
|                   |    __.--" , ; `"=._o." ,-"""-._ ".   |
|___________________|_._"  ,. .` ` `` ,  `"-._"-._   ". '__|___________________
          |           |o`"=._` , "` `; .". ,  "-._"-._; ;              |
 _________|___________| ;`-.o`"=._; ." ` '`."\` . "-._ /_______________|_______
|                   | |o;    `"-.o`"=._``  '` " ,__.--o;   |
|___________________|_| ;     (#) `-.o `"=.`_.--"_o.-; ;___|___________________
____/______/______/___|o;._    "      `".o|o_.--"    ;o;____/______/______/____
/______/______/______/_"=._o--._        ; | ;        ; ;/______/______/______/_
____/______/______/______/__"=._o--._   ;o|o;     _._;o;____/______/______/____
/______/______/______/______/____"=._o._; | ;_.--"o.--"_/______/______/______/_
____/______/______/______/______/_____"=.o|o_.--""___/______/______/______/____
/______/______/______/______/______/______/______/______/______/______/_____ /
*******************************************************************************
''')
print("Welcome to Treasure Island.")
print("Your mission is to find the treasure.\n") 
choice1 = input('Now, where do you want to go from here? Type "left" or "right".\n').lower()

if choice1 == "left":
  choice2 = input('You\'ve just arrived the middle of the lake...Type "swim" to swim across the lake or Type "wait" to wait for the boat\n').lower()
  if choice2 == "wait":
    choice3 = input('You\'ve arrived at the Treasure Island safely. There is a house with 3 doors..."red", "yellow"and "blue", which door will you choose?\n').lower()
    if choice3 == "red":
      print('It\'s a fire room and you\'ve been burnt!. GAME OVER!!!')
    elif choice3 == 'yellow':
      print('Woohoo! You\'ve found the Treasure! You Win!')
    elif choice3 == 'blue':
      print('You\'ve entered a room of beasts and you\'ve been eaten by beasts!. GAME OVER!!!.')
    else:
      print('You choose a door that doesn\'t exist. GAME OVER!!!.')
  else:
    print('You\'ve just been attacked by a trout. Game Over!.')
else:
  message = ('You just fell into a hole!. Game Over!...You can try again!')
  print(message)